### ISSUE TITLE
Send non switch RF codes

### ISSUE THREAD

**Issue by protolyser** [nobodyMO/node-red-contrib-rcswitch2#2]
Thanks for the great plugin it works perfectly for my RF sockets.
I also have a motorized screen with RF remote. I don't have binary dip codes there.
Via 

```
git clone --recursive https://github.com/ninjablocks/433Utils.git
cd 433Utils/RPi_utils
make all
sudo ./RFSniffer
```

and a rf receiver I got this codes for my remote:

```
Up 8066129
Stop 8066130
Down 8066132
```

How can I send this with rcswitch2?

**Comment by nobodyMO** [comment]
hi protolyser,

I haven't used ninja block codes, so I'm not shure if they will work with rcswitch or not. 
You can try to convert them from decimal to binary (e.g. with the windows calculator in programmer mode) and send them as binary string. 

Up 11110110001010001010001      or    011110110001010001010001 (leading 0 for 24 bit lengh)
Stop 11110110001010001010010   or    011110110001010001010010
Down 11110110001010001010100 or    011110110001010001010100

Maybe it works.

**Comment by protolyser** [comment]
can't get that to work. is there another way to sniff RF codes via 433mhz receiver to get the correct binary codes?

EDIT: the 24bit binary codes were correct (011110110001010001010001). I had a too far distance from the motor screen. it works perfectly now :)
Thanks for the help and the awesome plugin
