### ISSUE TITLE
Fails to install 

### ISSUE THREAD

**Issue by ceinem** [nobodyMO/node-red-contrib-rcswitch2#5]
I get the following error when I try to install it. I tried with sudo, as root user, with unsafe-perm nothing worked. 
Similar error is reported https://github.com/marvinroger/node-rcswitch/issues/15

> rcswitch@0.3.1 install /home/pi/node_modules/rcswitch
> node-gyp rebuild

make: Verzeichnis „/home/pi/node_modules/rcswitch/build“ wird betreten
  CXX(target) Release/obj.target/rcswitch/src/rcswitch.o
  CXX(target) Release/obj.target/rcswitch/src/RCSwitchNode.o
../src/RCSwitchNode.cpp: In static member function ‘static void RCSwitchNode::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/RCSwitchNode.cpp:83:59: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [0])’
     info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                           ^
In file included from /root/.node-gyp/10.10.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/RCSwitchNode.h:4,
                 from ../src/RCSwitchNode.cpp:1:
/root/.node-gyp/10.10.0/include/node/v8.h:3989:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.10.0/include/node/v8.h:3989:44: note:   candidate expects 3 arguments, 2 provided
/root/.node-gyp/10.10.0/include/node/v8.h:3992:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/root/.node-gyp/10.10.0/include/node/v8.h:3992:44: note:   candidate expects 1 argument, 2 provided
rcswitch.target.mk:103: die Regel für Ziel „Release/obj.target/rcswitch/src/RCSwitchNode.o“ scheiterte
make: *** [Release/obj.target/rcswitch/src/RCSwitchNode.o] Fehler 1
make: Verzeichnis „/home/pi/node_modules/rcswitch/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.69-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/rcswitch
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rcswitch@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rcswitch@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-16T13_06_14_018Z-debug.log

**Comment by nobodyMO** [comment]
Due to holidays I can't answer earlier.
The node-red adapter has a dependency on the npm package rcswitch, which is on github marvinroger/node-rcswitch.
As you already wrote, there is an error when compiling the C libraries of this package. 
If the problem is solved there, the installation of the node red adapter should work again.

**Comment by nobodyMO** [comment]
Version 0.5.0 now suports nodejs up to 12
